### ISSUE TITLE
attempt to index field 'running_var'

### ISSUE THREAD

**Issue by RetrieverJo** [xternalz/DelugeNets#1]
Hi, I'm trying to test your network, however I got an error while running "DelugeNet-146 on CIFAR-10"

I created docker image myself for CUDA 7.0 + CUDNN 4.0 + Torch + fb.resnet.torch,
and I checked the fb.resnet.torch works well.
However, when I put your model files to models/ and run your CIFAR train command, it returns an error.

following messages are the error, I don't know how to treat that.
Do you have any solution?

> root@a041bf04ed08:~/fb.resnet.torch# th main.lua -batchSize 64 -nEpochs 300 -optnet true -netType delugenet -dataset cifar10 -depth 146.1
=> Creating model from file: models/delugenet.lua	
 | DelugeNet-146.1 CIFAR-10	
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 2 module of nn.Sequential:
In 3 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 1 module of nn.Sequential:
./models/CrossLayerDepthwiseConvolution.lua:54: attempt to index field 'running_var' (a nil value)
stack traceback:
	./models/CrossLayerDepthwiseConvolution.lua:54: in function <./models/CrossLayerDepthwiseConvolution.lua:45>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function </root/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	...
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	/root/torch/install/share/lua/5.1/optnet/init.lua:387: in function 'optimizeMemory'
	./models/init.lua:47: in function 'setup'
	main.lua:33: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	/root/torch/install/share/lua/5.1/optnet/init.lua:387: in function 'optimizeMemory'
	./models/init.lua:47: in function 'setup'
	main.lua:33: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
root@a041bf04ed08:~/fb.resnet.torch#

**Comment by xternalz** [comment]
Please try updating Torch packages to the latest versions.

**Comment by RetrieverJo** [comment]
@xternalz 
I ran 'luarocks install torch', it still returns same error.
But during that command, building process showing log about failing to find "MKL library".
Is that mandatary?

**Comment by xternalz** [comment]
You have to update more than just the `torch` package (`cutorch, nn, cunn, cudnn, ...`). The easiest way is to reinstall Torch according to the official guide [http://torch.ch/docs/getting-started.html#_](http://torch.ch/docs/getting-started.html#_).

**Comment by RetrieverJo** [comment]
I started with clecn ubuntu 14.04 + CUDA7.0 + CUDNN4 docker image, so everything about torch is based on [fb.resnet.torch install instruction](https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md).

should I update everything?

**Comment by xternalz** [comment]
cuDNN v4 is obsolete, please opt for cuDNN v5 and the latest Torch's `cudnn` package from `master` branch.

**Comment by RetrieverJo** [comment]
Got it. Because of the fb.resnet.torch install instruction guided with v4, I installed that version.
After update to v5, cudnn package, I will let you know.
Thanks for your help.

**Comment by RetrieverJo** [comment]
I updated CUDA to 7.5 and CUDNN to 5.1, I works well.
Thanks @xternalz .
I will close this issue.
